//! Golden test: the Rust LZW decoder must reproduce the Python decoder's
//! output byte-for-byte on real Blitzortung frames captured from the live
//! feed (`fixtures/frames.json`, generated by `capture_fixtures.py`).

use chrono::{TimeZone, Utc};
use lightning_core::{decode_frame, lzw, Recovery};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    compressed: String,
    decoded: String,
    time: i128,
    lat: f64,
    lon: f64,
    stations: usize,
}

fn fixtures() -> Vec<Fixture> {
    let raw = include_str!("fixtures/frames.json");
    serde_json::from_str(raw).expect("fixtures/frames.json is valid")
}

#[test]
fn lzw_matches_python_decoder_on_every_real_frame() {
    let fx = fixtures();
    assert!(
        fx.len() >= 30,
        "expected a meaningful fixture set, got {}",
        fx.len()
    );
    for (i, f) in fx.iter().enumerate() {
        let got = lzw::decode(&f.compressed);
        assert_eq!(got, f.decoded, "frame {i}: LZW output diverged from Python");
    }
}

#[test]
fn every_real_frame_decodes_to_exact_strike_without_recovery() {
    let fx = fixtures();
    // Fixtures were captured ~2026-09-14T13:40Z; use a "now" inside the window
    // so the 24h drift guard is exercised realistically.
    let first_time_ns = fx[0].time;
    let now = Utc
        .timestamp_opt((first_time_ns / 1_000_000_000) as i64, 0)
        .single()
        .unwrap();

    for (i, f) in fx.iter().enumerate() {
        let (strike, rec) = decode_frame(&f.compressed, now)
            .unwrap_or_else(|e| panic!("frame {i} failed to decode: {e}"));
        assert_eq!(
            rec,
            Recovery::Exact,
            "frame {i}: recovery should never fire on LZW path"
        );
        assert_eq!(
            strike.strike_time as i128, f.time,
            "frame {i}: epoch mismatch"
        );
        assert_eq!(strike.latitude, f.lat, "frame {i}: lat mismatch");
        assert_eq!(strike.longitude, f.lon, "frame {i}: lon mismatch");
        assert_eq!(
            strike.stations,
            Some(f.stations as i16),
            "frame {i}: station count mismatch"
        );
        assert_eq!(
            f.time.to_string().len(),
            19,
            "frame {i}: fixture epoch not 19 digits"
        );
    }
}

#[test]
fn garbage_frame_is_an_error_not_a_panic() {
    let now = Utc::now();
    assert!(decode_frame("not json at all", now).is_err());
    assert!(decode_frame("", now).is_err());
}
